name: Cypress Component Tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install
          npm list cypress || echo "Cypress installation verified"
      
      - name: Copy JSON files and prepare test environment
        run: |
          mkdir -p server/dist/seeds
          cp server/src/seeds/*.json server/dist/seeds/ || echo "No JSON files to copy (this is just a precaution)"
      
      - name: Run Cypress component tests
        run: npm run test-component
        env:
          CYPRESS_VERIFY_TIMEOUT: 100000