name: Deploy to Render

on:
  push:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Render
        run: |
          echo "Triggering Render deployment webhook..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      
      - name: Deployment Status
        run: |
          echo "Deployment triggered successfully!"
          echo "Your application is being deployed to Render."
          echo "This may take a few minutes to complete."